# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="blockhunt"
version="${file.jarVersion}"
displayName="BlockHunt"
credits="Chase"
authors="Chase<chase@mailbox.org>"
description='''
Minecraft minigame. Hunt for a randomly selected block
'''
[[dependencies.blockhunt]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blockhunt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
